### ISSUE TITLE
Use return_pandas method?

### ISSUE THREAD

**Issue by bmschmidt** [organisciak/BookwormPython#1]
This might be better filed as an issue on BookwormAPI called "Should return_pandas method be retired?", but I just want to get your thoughts without spamming everyone, so filing it as a feature request insincerely.

You say here that JSON is "more transparent and safer."

```
    def _fetch(self, query, type="pandas"):
        ''' Get results from a bookworm Server
            This method calls JSON and converts to Pandas, rather than using
            Bookworm's built-in DataFrame return method, as JSON is a more
            transparent and safer format for data interchange.
```

Care to elucidate? If you're right, it might make sense simply to retire the return_pandas method entirely (it's never been fully documented): the two uses cases for it I can think of are
1. This one: a numpy based set of code for using the API
2. As the internal interchange format in a meta-Bookworm aggregating across servers.

If it's not safe enough to use for 1, as you imply, it might not be safe enough for number 2 either. So what are the safety issues involved?

**Comment by organisciak** [comment]
A pickle can theoretically be used to run arbitrary code, so a man in the middle attack can theoretically create a lot of damage. It's likely the pandas pickle isn't being transmitted over HTTPS, right?

In reality, I don't think the security issue is likely to be taken advantage of, security through obscurity and all that. I stuck with JSON because of the security risk _in combination_ with the fact that JSON is easier for another person to trust and easier to debug.

I like use case #2 for return_pickle, especially for large objects. It would be important to have secure connections, otherwise that could be a server backdoor.
